language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm
  
env:
  - DB=mysql
  - DB=mysqli
  - DB=sqlite
  - DB=pdo/mysql
  - DB=pdo/sqlite

sudo: false

before_script:
  - sh -c "composer install --dev --no-progress"
  - sh -c "if [ '$DB' = 'mysql' ] || [ '$DB' = 'mysqli' ] || [ '$DB' = 'pdo/mysql' ]; then mysql -e 'create database IF NOT EXISTS avl_test;'; fi"

script: phpunit -d zend.enable_gc=0 -d date.timezone=UTC --coverage-text --configuration tests/travis/$DB.phpunit.xml

matrix:
  allow_failures:
    - php: hhvm
  exclude:
    - php: 7
      env: DB=mysql

notifications:
  email: false